---
- name: check that dns is functioning correctly
  block:
    - name: perform dns lookup by ip
      command: host {{ test_ip }}
      register: lookup_by_ip
      changed_when: no

    - set_fact:
        lookup_regex: .*in-addr.arpa domain name pointer ({{ test_hostname | regex_escape }})\.({{ domain | regex_escape }})\.

    - set_fact:
        lookup_match: "{{ lookup_by_ip.stdout | regex_findall(lookup_regex) }}"

    - set_fact:
        lookup_hostname: "{{ lookup_match[0][0] }}"
        lookup_domainname: "{{ lookup_match[0][1] }}"

    - name: perform dns lookup by hostname
      command: host {{ lookup_hostname }}.{{ domain }}
      register: lookup_by_hostname
      changed_when: no

    - name: check that the returned ip address is correct
      fail:
        msg: received incorrect ip on lookup by hostname
      when: not (lookup_by_hostname.stdout | regex_search(lookup_hostname + '.' + lookup_domainname + ' has address ' + (test_ip | regex_escape())))
  rescue:
    - fail:
        msg: forward and reverse dns are required to be functioning correctly for this system
  vars:
    test_host: "{{ groups['rhhi-hosts'] | reject('equalto', inventory_hostname) | map('extract', hostvars) | first }}"
    test_ip: "{{ test_host['ansible_host'] }}"
    test_hostname: "{{ test_host['inventory_hostname'] }}"
  run_once: yes
