---
- name: verify state of gluster setup by probing all peers
  command: gluster peer probe {{ item }}
  changed_when: no
  when: gluster_configured or (gdeploy_run | succeeded)
  with_items: "{{ rhhi_host_list | rejectattr('glu_ip', 'equalto', glu_ip) | map(attribute='glu_ip') | list }}"
