---
- name: check that each node has required variables set
  fail:
    msg: missing required variable '{{ item }}'
  when: item not in hostvars[inventory_hostname]
  with_items:
    - pod_location
    - domain
    - dns
    - hostname
    - ip_prefix_length
    - vm_ip
    - glu_ip

- name: check that there is a target machine
  fail:
    msg: host '{{ inventory_hostname }}' is not in the rhhi-install-target inventory group
  when: inventory_hostname not in groups['rhhi-install-target']
  run_once: yes

- name: check that the gluster_raid_type (raid type) is valid
  fail:
    msg: gluster_raid_type invalid
  when: gluster_raid_type not in ['jbod', 'raid5', 'raid6']
  run_once: yes

- name: check that the gluster_raid_stripe_size is valid
  fail:
    msg: gluster_raid_stripe_size invalid
  when: gluster_raid_stripe_size <= 0
  run_once: yes

- name: check that the gluster_raid_data_disk_count is valid
  fail:
    msg: gluster_raid_data_disk_count invalid
  when: gluster_raid_data_disk_count <= 0
  run_once: yes
