---
- name: perform pre checks
  include_tasks: checks/pre.yml
  tags: ['checks']

- name: ensure the node has the correct hostname and domain
  command: hostnamectl set-hostname {{ hostname }}.{{ domain }}

- name: run all tasks related to subscription management
  include_tasks: rhsm.yml
  tags: ['rhsm']

- name: run all tasks related to configuring ssh
  include_tasks: ssh.yml
  tags: ['ssh']

- name: perform post checks
  include_tasks: checks/post.yml
  tags: ['checks']
