---
- name: perform pre-flight checks
  hosts: rhhi-hosts
  connection: local
  gather_facts: no
  pre_tasks:
    - include_tasks: tasks/pre-flight-checks.yml


- name: ensure all physical rhhi nodes have the correct baseline configuration
  hosts: rhhi-hosts
  gather_facts: yes
  remote_user: root
  pre_tasks:
    - set_fact:
        ansible_ssh_private_key_file: "{{ rhhi_ssh_private_key_path }}"
  roles:
    - rhhi-host


- name: configure gluster on install target rhhi host
  hosts: rhhi-hosts:&rhhi-install-target
  gather_facts: yes
  remote_user: root
  roles:
    - rhhi-install-target
    - gluster
