---
- name: perform pre checks
  include_tasks: checks/pre.yml
  tags: ['checks']

- name: install gluster
  include_tasks: install.yml

- name: perform post checks
  include_tasks: checks/post.yml
  tags: ['checks']
