---
- include_tasks: checks.yml
- name: create gdeploy config file
  template:
    src: gdeploy.conf.j2
    dest: /tmp/gdeploy.conf
  vars:
    rhhi_host_list: "{{ groups['rhhi-hosts']|map('extract', hostvars)|list }}"
    unique_brick_device_names: "{{ [brick_engine_device_name, brick_data_device_name, brick_vmstore_device_name] | unique }}"
